### ISSUE TITLE
set up circle

### ISSUE THREAD

**Issue by lortza** [lortza/blamegame#3]
started process here: https://app.circleci.com/pipelines/github/lortza/voting_game

base build config
```yml
version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
```

- [x] set up circle
- [x] comment or `x` out WIP tests
- [x] set up [heroku to deploy after CI passes](https://dashboard.heroku.com/apps/blamegame/deploy/github)
- [x] add icons to readme
